version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/codedeploy-code/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
     - location: scripts/after_install.sh
       timeout: 300

